// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from "next";

type Data = {
  _id: number;
  title: string;
  description: string;
  oldPrice: number;
  price: number;
  category: string;
  subCategory: string;
  features: string;
  brand: string;
  images: string[];
  isNew: boolean;
  sponsored: boolean;
  deals: boolean;
  newDeals: boolean;
  flashSale: boolean;
  itemsLeft?: number; // Optional, only applies if flashSale is true
  quantity:number,
  variations?: string[]; // Optional, applies if product has different variations
  warranty: boolean;
  warrantyPeriod?: string; // Optional, only applies if warranty is true
  officialStore: boolean;
}[];

const productsData = [
  {
    _id: 101,
    title: "Samsung Galaxy S23 Ultra",
    description:
      "The latest Samsung flagship with an advanced 200MP camera, Snapdragon 8 Gen 2, and stunning AMOLED display.",
    oldPrice: 1199.99,
    price: 999.99,
    category: "Electronics",
    subCategory: "Smartphones",
    features: "200MP Camera, 5000mAh Battery, S-Pen, Snapdragon 8 Gen 2",
    brand: "Samsung",
    images: [
      "https://s.alicdn.com/@sc04/kf/H160fe461dae2484d80e1ca0ae1151a01r.jpg_720x720q50.jpg",
      "https://s.alicdn.com/@sc04/kf/H8316297b9832491999dfde17dc4a1c6f5.jpg_720x720q50.jpg",
      "https://s.alicdn.com/@sc04/kf/H591280d10aa84ba7b832545ed518130er.jpg_720x720q50.jpg",
      "https://s.alicdn.com/@sc04/kf/H0c674d219e34407ba494f948e2f4643d3.jpg_720x720q50.jpg"
    ],
    isNew: true,
    sponsored: true,
    deals: true,
    newDeals: false,
    flashSale: true,
    itemsLeft: 20,
    quantity:1,
    variations: ["256GB", "512GB", "1TB"],
    warranty: true,
    warrantyPeriod: "2 Years",
    officialStore: true,
  },
  {
    _id: 102,
    title: "Nike Air Jordan 1 Retro",
    description:
      "Iconic basketball sneakers with high ankle support and premium leather.",
    oldPrice: 200.0,
    price: 149.99,
    category: "Fashion",
    subCategory: "Shoes",
    features: "Leather build, high ankle support, Air cushioning",
    brand: "Nike",
    images: [
      "https://s.alicdn.com/@sc04/kf/Hf514696ec9a24ac28bd3b0afc4bbbc7c1.jpg_720x720q50.jpg",
      "https://s.alicdn.com/@sc04/kf/H7ff9d76f935445b9a8d40a5b6e4413c3C.jpg_720x720q50.jpg",
      "https://s.alicdn.com/@sc04/kf/Ha0b0fcd7aa404b279d2dd2f97b0a33cdO.jpg_720x720q50.jpg",
      "https://s.alicdn.com/@sc04/kf/H1aff4cd1881541d7abb0bb88c095f81aq.jpg_720x720q50.jpg",
      "https://s.alicdn.com/@sc04/kf/H0c8cafda89d84da1bf5a09e834cdb7568.jpg_720x720q50.jpg"
    ],
    isNew: false,
    sponsored: true,
    deals: true,
    newDeals: true,
    flashSale: false,
    itemsLeft: 20,
    quantity:1,
    variations: ["Size 9", "Size 10", "Size 11"],
    warranty: false,
    warrantyPeriod: "N/A",
    officialStore: false,
  },
  {
    _id: 103,
    title: "Apple MacBook Pro M2",
    description:
      "Powerful laptop with Apple's M2 chip, Retina display, and all-day battery life.",
    oldPrice: 1999.99,
    price: 1799.99,
    category: "Electronics",
    subCategory: "Laptops",
    features: "M2 chip, 16GB RAM, 512GB SSD, Retina Display",
    brand: "Apple",
    images: [
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/46/3935803/1.jpg?4568",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/46/3935803/2.jpg?4568",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/46/3935803/3.jpg?4568",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/46/3935803/4.jpg?4568"
    ],
    isNew: true,
    sponsored: false,
    deals: true,
    newDeals: false,
    flashSale: true,
    itemsLeft: 10,
    quantity:1,
    variations: ["512GB SSD", "1TB SSD"],
    warranty: true,
    warrantyPeriod: "1 Year",
    officialStore: true,
  },

  {
    _id: 104,
    title: "Sony WH-1000XM5 Wireless Headphones",
    description:
      "Industry-leading noise cancellation headphones with 30-hour battery life.",
    oldPrice: 399.99,
    price: 349.99,
    category: "Electronics",
    subCategory: "Headphones",
    features: "ANC, 30-hour battery, Bluetooth 5.0, Touch Controls",
    brand: "Sony",
    images: [
      "https://ke.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/44/9698052/1.jpg?5909",
      "https://ke.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/73/4974772/1.jpg?7931",
      "https://ke.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/68/4747061/1.jpg?1584",
    ],
    isNew: true,
    sponsored: true,
    deals: false,
    newDeals: false,
    flashSale: true,
    itemsLeft: 50,
    quantity:1,
    variations: ["Black", "Silver"],
    warranty: true,
    warrantyPeriod: "1 year",
    officialStore: true,
  },
  {
    _id: 105,
    title: "Adidas Ultraboost 22",
    description:
      "High-performance running shoes with responsive Boost cushioning.",
    oldPrice: 180.0,
    price: 129.99,
    category: "Fashion",
    subCategory: "Shoes",
    features: "Boost cushioning, Primeknit upper, Flexible outsole",
    brand: "Adidas",
    images: [
      "https://ke.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/88/2555591/1.jpg?1524",
      "https://ke.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/30/1438661/1.jpg?1342",
      "https://ke.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/52/1438661/1.jpg?1341",
    ],
    isNew: false,
    sponsored: false,
    deals: true,
    newDeals: true,
    flashSale: false,
    itemsLeft: 0,
    quantity:1,
    variations: ["Black", "White", "Blue"],
    warranty: true,
    warrantyPeriod: "6 months",
    officialStore: true,
  },
  {
    _id: 106,
    title: "Apple iPad Pro 12.9-inch M2",
    description:
      "The most powerful iPad ever, featuring the M2 chip and Liquid Retina XDR display.",
    oldPrice: 1299.99,
    price: 1099.99,
    category: "Electronics",
    subCategory: "Tablets",
    features: "M2 chip, 120Hz ProMotion, Face ID, 5G support",
    brand: "Apple",
    images: [
      "https://ke.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/10/5318972/1.jpg?9591",
      "https://ke.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/66/7445972/1.jpg?1464",
      "https://ke.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/48/8844972/1.jpg?4167",
    ],
    isNew: true,
    sponsored: true,
    deals: true,
    newDeals: false,
    flashSale: true,
    itemsLeft: 30,
    quantity:1,
    variations: ["Space Gray", "Silver"],
    warranty: true,
    warrantyPeriod: "2 years",
    officialStore: true,
  },

  {
    _id: 107,
    title: "Luxury Leather Handbag",
    description:
      "Elegant and stylish genuine leather handbag with gold detailing.",
    oldPrice: 250.0,
    price: 189.99,
    category: "Fashion",
    subCategory: "Accessories",
    features: "Genuine leather, Adjustable strap, Multiple compartments",
    brand: "Louis Vuitton",
    images: [
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/95/8599671/1.jpg?5229",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/95/8599671/3.jpg?5229",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/95/8599671/5.jpg?5229",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/95/8599671/3.jpg?5229",
    ],
    isNew: true,
    sponsored: false,
    deals: false,
    newDeals: true,
    flashSale: false,
    itemsLeft: 0,
    quantity:1,
    variations: ["Black", "Brown", "Red"],
    warranty: true,
    warrantyPeriod: "1 year",
    officialStore: true,
  },
  {
    _id: 108,
    title: "Samsung 65-inch QLED 4K TV",
    description:
      "Crystal-clear 4K visuals with Quantum Dot technology and HDR support.",
    oldPrice: 1299.99,
    price: 999.99,
    category: "Electronics",
    subCategory: "TVs",
    features: "4K UHD, QLED, HDR10+, Smart TV",
    brand: "Samsung",
    images: [
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/68/9929992/1.jpg?5317",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/68/9929992/2.jpg?5317",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/68/9929992/3.jpg?5317",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/68/9929992/4.jpg?5317",
    ],
    isNew: false,
    sponsored: true,
    deals: true,
    newDeals: false,
    flashSale: true,
    itemsLeft: 20,
    quantity:1,
    variations: ["65-inch", "75-inch", "85-inch"],
    warranty: true,
    warrantyPeriod: "2 years",
    officialStore: true,
  },
  {
    _id: 109,
    title: "Dyson Airwrap Complete",
    description:
      "High-tech hair styling tool with multiple attachments for curls, waves, and smooth blowouts.",
    oldPrice: 599.99,
    price: 499.99,
    category: "Beauty & Personal Care",
    subCategory: "Hair Styling Tools",
    features: "Multiple attachments, Heat control, Airwrap technology",
    brand: "Dyson",
    images: [
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/38/2149003/2.jpg?6175",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/38/2149003/5.jpg?6175",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/38/2149003/6.jpg?6175",
    ],
    isNew: true,
    sponsored: false,
    deals: true,
    newDeals: false,
    flashSale: true,
    itemsLeft: 15,
    quantity:1,
    variations: ["Pink", "Blue", "Black"],
    warranty: true,
    warrantyPeriod: "1 year",
    officialStore: false,
  },

  {
    _id: 110,
    title: "Christmas Gift Set - Perfume & Skincare",
    description:
      "Luxury perfume and skincare gift set, perfect for the holiday season.",
    oldPrice: 150.0,
    price: 99.99,
    category: "Seasonal Deals",
    subCategory: "Gift Sets",
    features: "Luxury perfume, Moisturizer, Holiday packaging",
    brand: "Chanel",
    images: [
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/06/6587403/1.jpg?4478",
      "https://ke.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/42/1028403/1.jpg?5544",
      "https://ke.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/51/3314682/1.jpg?5696",
    ],
    isNew: true,
    sponsored: false,
    deals: true,
    newDeals: true,
    flashSale: true,
    itemsLeft: 50,
    quantity:1,
    variations: ["Standard"],
    warranty: false,
    warrantyPeriod: "N/A",
    officialStore: false,
  },
  {
    _id: 201,
    title: "Apple iPhone 15 Pro Max",
    description:
      "Latest iPhone with A17 Pro chip, titanium design, and 48MP camera.",
    oldPrice: 1299.99,
    price: 1199.99,
    category: "Electronics",
    subCategory: "Smartphones",
    features: "A17 Pro chip, 48MP Camera, USB-C, Titanium Build",
    brand: "Apple",
    images: [
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/94/2367191/1.jpg?4945",
      "https://ke.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/28/5570761/1.jpg?1845",
      "https://ke.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/79/8370761/1.jpg?0761",
    ],
    isNew: true,
    sponsored: true,
    deals: true,
    newDeals: false,
    flashSale: false,
    itemsLeft: 0,
    quantity:1,
    variations: ["128GB", "256GB", "512GB", "1TB"],
    warranty: true,
    warrantyPeriod: "1 Year",
    officialStore: true,
  },
  {
    _id: 202,
    title: "Dell XPS 15",
    description:
      "Premium laptop with Intel Core i9, 32GB RAM, and 4K OLED display.",
    oldPrice: 2299.99,
    price: 1999.99,
    category: "Electronics",
    subCategory: "Laptops",
    features: "Intel i9, 32GB RAM, 1TB SSD, 4K OLED Touchscreen",
    brand: "Dell",
    images: [
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/28/115756/1.jpg?1847",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/28/115756/2.jpg?1847",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/28/115756/3.jpg?1847",
    ],
    isNew: true,
    sponsored: false,
    deals: true,
    newDeals: true,
    flashSale: true,
    itemsLeft: 25,
    quantity:1,
    variations: ["16GB RAM", "32GB RAM"],
    warranty: true,
    warrantyPeriod: "2 Years",
    officialStore: true,
  },

  {
    _id: 203,
    title: "Adidas Yeezy Boost 350 V2",
    description: "Limited edition sneakers designed for comfort and style.",
    oldPrice: 250.0,
    price: 199.99,
    category: "Fashion",
    subCategory: "Shoes",
    features: "Primeknit upper, Boost cushioning, Slip-on fit",
    brand: "Adidas",
    images: [
      "https://ke.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/84/3770761/1.jpg?7816",
      "https://ke.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/90/643837/1.jpg?0845",
    ],
    isNew: false,
    sponsored: true,
    deals: false,
    newDeals: true,
    flashSale: false,
    itemsLeft: 0,
    quantity:1,
    variations: ["US 8", "US 9", "US 10", "US 11"],
    warranty: false,
    warrantyPeriod: "N/A",
    officialStore: false,
  },
  {
    _id: 204,
    title: "Sony PlayStation 5",
    description: "Next-gen gaming console with ultra-fast SSD and 4K gaming.",
    oldPrice: 599.99,
    price: 499.99,
    category: "Gaming",
    subCategory: "Consoles",
    features: "8K Output, Ray Tracing, DualSense Controller",
    brand: "Sony",
    images: [
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/74/3165861/1.jpg?7248",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/94/1440052/1.jpg?1710",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/94/1440052/2.jpg?1710",
    ],
    isNew: false,
    sponsored: true,
    deals: true,
    newDeals: false,
    flashSale: true,
    itemsLeft: 10,
    quantity:1,
    variations: ["Disc Edition", "Digital Edition"],
    warranty: true,
    warrantyPeriod: "1 Year",
    officialStore: true,
  },
  {
    _id: 205,
    title: "Bose QuietComfort Ultra Headphones",
    description:
      "Industry-leading noise cancellation with premium sound quality.",
    oldPrice: 399.99,
    price: 349.99,
    category: "Electronics",
    subCategory: "Headphones",
    features: "Active Noise Cancellation, 24-hour battery, Bluetooth 5.3",
    brand: "Bose",
    images: [
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/65/7790152/1.jpg?4652",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/65/7790152/2.jpg?4652",
    ],
    isNew: true,
    sponsored: false,
    deals: true,
    newDeals: true,
    flashSale: false,
    itemsLeft: 0,
    quantity:1,
    variations: ["Black", "Silver"],
    warranty: true,
    warrantyPeriod: "1 Year",
    officialStore: true,
  },

  {
    _id: 206,
    title: "Apple Watch Series 9",
    description:
      "Advanced health tracking and fitness smartwatch with new S9 chip.",
    oldPrice: 499.99,
    price: 429.99,
    category: "Electronics",
    subCategory: "Wearables",
    features: "Blood Oxygen Monitoring, ECG, Always-On Display",
    brand: "Apple",
    images: [
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/17/8050722/1.jpg?0874",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/17/8050722/2.jpg?0874",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/17/8050722/3.jpg?0874",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/17/8050722/4.jpg?0874",
    ],
    isNew: true,
    sponsored: true,
    deals: false,
    newDeals: false,
    flashSale: false,
    itemsLeft: 15,
    quantity:1,
    variations: ["Midnight", "Starlight", "Silver", "Red"],
    warranty: true,
    warrantyPeriod: "1 Year",
    officialStore: true,
  },
  {
    _id: 207,
    title: "The North Face Nuptse Jacket",
    description:
      "Iconic puffer jacket with down insulation for extreme weather conditions.",
    oldPrice: 320.0,
    price: 249.99,
    category: "Fashion",
    subCategory: "Outerwear",
    features: "Goose Down, Water-resistant, Packable Design",
    brand: "The North Face",
    images: [
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/29/4766511/7.jpg?5251",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/29/4766511/6.jpg?5251",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/29/4766511/1.jpg?5251",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/29/4766511/2.jpg?5251",
    ],
    isNew: false,
    sponsored: false,
    deals: true,
    newDeals: true,
    flashSale: true,
    itemsLeft: 8,
    quantity:1,
    variations: ["Black", "Blue", "Red"],
    warranty: false,
    warrantyPeriod: "N/A",
    officialStore: false,
  },
  {
    _id: 208,
    title: "Samsung 75-inch Neo QLED 8K TV",
    description:
      "Experience stunning visuals with 8K resolution and Quantum Dot technology.",
    oldPrice: 4999.99,
    price: 3999.99,
    category: "Electronics",
    subCategory: "TVs",
    features: "8K Resolution, HDR10+, Smart TV, 120Hz Refresh Rate",
    brand: "Samsung",
    images: [
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/80/6239992/1.jpg?8013",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/80/6239992/2.jpg?8013",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/80/6239992/3.jpg?8013",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/80/6239992/5.jpg?8013",
    ],
    isNew: true,
    sponsored: true,
    deals: true,
    newDeals: false,
    flashSale: false,
    itemsLeft: 5,
    quantity:1,
    variations: ["Standard", "Deluxe Package"],
    warranty: true,
    warrantyPeriod: "2 Years",
    officialStore: true,
  },

  {
    _id: 209,
    title: "KitchenAid Artisan Stand Mixer",
    description:
      "Powerful kitchen mixer with 10-speed settings and multiple attachments.",
    oldPrice: 499.99,
    price: 429.99,
    category: "Home & Kitchen",
    subCategory: "Appliances",
    features: "5-quart capacity, Stainless Steel Bowl, Tilt-Head Design",
    brand: "KitchenAid",
    images: [
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/72/3205582/1.jpg?8327",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/72/3205582/2.jpg?8327",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/72/3205582/3.jpg?8327",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/72/3205582/4.jpg?8327",
    ],
    isNew: true,
    sponsored: false,
    deals: true,
    newDeals: true,
    flashSale: true,
    itemsLeft: 20,
    quantity:1,
    variations: ["Red", "Black", "Silver"],
    warranty: true,
    warrantyPeriod: "1 Year",
    officialStore: true,
  },
];

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<Data>
) {
  res.status(200).json(productsData);
}
